/**
 * sync-index.mjs — injects prompts + token counts into index.html.
 *
 * Run: npm run sync
 *
 * Flow:
 *   llms.txt  ──read──▶  prompts.mjs  ──import──▶  this script
 *                                                       │
 *                                              count tokens
 *                                                       │
 *                                          replace SYNC block in index.html
 *
 * Only edit llms.txt or prompts.mjs. Never edit the SYNC block in index.html manually.
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { countTokens as openaiCount } from 'gpt-tokenizer/encoding/o200k_base';
import { countTokens as anthropicCount } from '@anthropic-ai/tokenizer';
import { SHORT_PROMPT, FULL_PROMPT } from './prompts.mjs';

const __dir = dirname(fileURLToPath(import.meta.url));
const indexPath = join(__dir, '../index.html');

// ── version sync ──────────────────────────────────────────────────────────────
const { version } = JSON.parse(readFileSync(join(__dir, '../package.json'), 'utf-8'));

function syncVersion(filePath) {
  let src = readFileSync(filePath, 'utf-8');
  // CDN URLs:  @m1kapp/maging@x.y.z
  src = src.replace(/@m1kapp\/maging@\d+\.\d+\.\d+/g, `@m1kapp/maging@${version}`);
  // version badges/labels:  v0.1.xx  (but NOT inside release-history data in stack.html)
  src = src.replace(/\bv\d+\.\d+\.\d+\b/g, `v${version}`);
  writeFileSync(filePath, src, 'utf-8');
  console.log(`✓  ${filePath.split('/').pop()} — version → v${version}`);
}

// index.html + demo.html 만 버전 교체 (stack.html 릴리즈 히스토리는 제외)
syncVersion(indexPath);
syncVersion(join(__dir, '../demo.html'));
// ─────────────────────────────────────────────────────────────────────────────

function escapeForTemplateLiteral(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
    .replace(/<\/script>/gi, '<\\/script>');
}

const short = {
  gpt: openaiCount(SHORT_PROMPT),
  claude: anthropicCount(SHORT_PROMPT),
};
short.gemini = Math.round(short.gpt * 1.06);

const full = {
  gpt: openaiCount(FULL_PROMPT),
  claude: anthropicCount(FULL_PROMPT),
};
full.gemini = Math.round(full.gpt * 1.06);

const block =
`  /* SYNC:START — auto-generated by \`npm run sync\`. Do not edit manually. */
  var SHORT_PROMPT = \`${escapeForTemplateLiteral(SHORT_PROMPT)}\`;
  var FULL_PROMPT = \`${escapeForTemplateLiteral(FULL_PROMPT)}\`;
  var TOKENS = {
    short: { gpt: ${short.gpt},  claude: ${short.claude},  gemini: ${short.gemini} },
    full:  { gpt: ${full.gpt}, claude: ${full.claude}, gemini: ${full.gemini} },
  };
  /* SYNC:END */`;

let html = readFileSync(indexPath, 'utf-8');

if (!html.includes('/* SYNC:START')) {
  console.error('✗  SYNC markers not found in index.html. Add /* SYNC:START */ ... /* SYNC:END */ first.');
  process.exit(1);
}

html = html.replace(/\/\* SYNC:START[\s\S]*?SYNC:END \*\//m, block);
writeFileSync(indexPath, html, 'utf-8');

console.log('');
console.log('✓  index.html synced');
console.log('');
console.log('   SHORT  →', SHORT_PROMPT.length.toLocaleString(), 'chars ·', short.claude, 'Claude tokens ·', short.gpt, 'GPT tokens');
console.log('   FULL   →', FULL_PROMPT.length.toLocaleString(), 'chars ·', full.claude, 'Claude tokens ·', full.gpt, 'GPT tokens');
console.log('');
