/**
 * sync-index.mjs — injects prompts + token counts into index.html.
 *
 * Run: npm run sync
 *
 * Flow:
 *   llms.txt  ──read──▶  prompts.mjs  ──import──▶  this script
 *                                                       │
 *                                              count tokens
 *                                                       │
 *                                          replace SYNC block in index.html
 *
 * Only edit llms.txt or prompts.mjs. Never edit the SYNC block in index.html manually.
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { countTokens as openaiCount } from 'gpt-tokenizer/encoding/o200k_base';
import { countTokens as anthropicCount } from '@anthropic-ai/tokenizer';
import {
  BASE_SHORT_DASHBOARD, BASE_FULL_DASHBOARD,
  BASE_SHORT_WEEKLY, BASE_FULL_WEEKLY,
  BASE_SHORT_LANDING, BASE_FULL_LANDING,
  SERVICE_RULES, LOGO_URL, HANDSHAKES,
} from './prompts.mjs';

const __dir = dirname(fileURLToPath(import.meta.url));
const indexPath = join(__dir, '../index.html');

// ── version sync ──────────────────────────────────────────────────────────────
const { version } = JSON.parse(readFileSync(join(__dir, '../package.json'), 'utf-8'));

function syncVersion(filePath) {
  let src = readFileSync(filePath, 'utf-8');
  src = src.replace(/@m1kapp\/maging@\d+\.\d+\.\d+/g, `@m1kapp/maging@${version}`);
  src = src.replace(/\bv\d+\.\d+\.\d+\b/g, `v${version}`);
  writeFileSync(filePath, src, 'utf-8');
  console.log(`✓  ${filePath.split('/').pop()} — version → v${version}`);
}

syncVersion(indexPath);
// ─────────────────────────────────────────────────────────────────────────────

function escapeForTemplateLiteral(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
    .replace(/<\/script>/gi, '<\\/script>');
}

// ── token counts (per service × mode × variant) ──
const services = ['flowai', 'claude', 'chatgpt', 'gemini'];
const bases = {
  dashboard: { short: BASE_SHORT_DASHBOARD, full: BASE_FULL_DASHBOARD },
  weekly:    { short: BASE_SHORT_WEEKLY,    full: BASE_FULL_WEEKLY },
  landing:   { short: BASE_SHORT_LANDING,   full: BASE_FULL_LANDING },
};

// flowai uses generic service rules (empty)
const svcRules = { flowai: '', ...SERVICE_RULES };

function compose(mode, variant, service) {
  const handshakeKey = mode === 'weekly-report' ? 'weekly' : mode;
  return bases[handshakeKey][variant] + svcRules[service] + HANDSHAKES[handshakeKey];
}

function countAll(mode, variant, service) {
  const text = compose(mode, variant, service);
  const gpt = openaiCount(text);
  const claude = anthropicCount(text);
  return { gpt, claude, gemini: Math.round(gpt * 1.06) };
}

// ── build SYNC block ──
const block = [
  '  /* SYNC:START — auto-generated by `npm run sync`. Do not edit manually. */',
];

// Base prompts (no service rules, no handshake)
for (const [mode, key] of [['dashboard', ''], ['weekly', '_WEEKLY'], ['landing', '_LANDING']]) {
  block.push(`  var SHORT_PROMPT${key} = \`${escapeForTemplateLiteral(bases[mode].short)}\`;`);
  block.push(`  var FULL_PROMPT${key} = \`${escapeForTemplateLiteral(bases[mode].full)}\`;`);
}

// Service rules
block.push(`  var SERVICE_RULES = {`);
for (const svc of services) {
  block.push(`    ${svc}: \`${escapeForTemplateLiteral(svcRules[svc])}\`,`);
}
block.push(`  };`);

// Handshakes (with logo)
block.push(`  var HANDSHAKES = {`);
for (const [mode, hs] of Object.entries(HANDSHAKES)) {
  block.push(`    ${mode}: \`${escapeForTemplateLiteral(hs)}\`,`);
}
block.push(`  };`);

// Token counts per service
block.push(`  var TOKENS_BY_SERVICE = {`);
for (const svc of services) {
  block.push(`    ${svc}: {`);
  for (const mode of ['dashboard', 'weekly', 'landing']) {
    const s = countAll(mode, 'short', svc);
    const f = countAll(mode, 'full', svc);
    block.push(`      ${mode}: { short: { gpt: ${s.gpt}, claude: ${s.claude}, gemini: ${s.gemini} }, full: { gpt: ${f.gpt}, claude: ${f.claude}, gemini: ${f.gemini} } },`);
  }
  block.push(`    },`);
}
block.push(`  };`);

// Backward compat
block.push(`  var TOKENS = TOKENS_BY_SERVICE.flowai.dashboard;`);
block.push(`  var TOKENS_WEEKLY = TOKENS_BY_SERVICE.flowai.weekly;`);
block.push(`  var TOKENS_LANDING = TOKENS_BY_SERVICE.flowai.landing;`);

block.push('  /* SYNC:END */');

const blockStr = block.join('\n');

let html = readFileSync(indexPath, 'utf-8');

if (!html.includes('/* SYNC:START')) {
  console.error('✗  SYNC markers not found in index.html. Add /* SYNC:START */ ... /* SYNC:END */ first.');
  process.exit(1);
}

html = html.replace(/\/\* SYNC:START[\s\S]*?SYNC:END \*\//m, blockStr);
writeFileSync(indexPath, html, 'utf-8');

console.log('');
console.log('✓  index.html synced');
console.log('');
for (const svc of services) {
  const f = countAll('dashboard', 'full', svc);
  console.log(`   ${svc.padEnd(8)} FULL → ${f.claude} Claude tokens · ${f.gpt} GPT tokens`);
}
console.log('');
